# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

env:
  NODE_VERSION: '12.x'
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{  env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - run: npm install -g morphir-elm
    - run: ls -al 
    - run: ls -al src
    - run: ls -al src/Morphir 
    - run: ls -al src/Morphir/Apps
    - run: morphir-elm make src/Morphir/Sample/Apps/morphir.json
